// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import { Document } from '@contentful/rich-text-types'

export interface IBankFields {
  /** Название */
  name?: string | undefined

  /** Логотип */
  logo?: Asset | undefined
}

export interface IBank extends Entry<IBankFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'bank'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IComandsFields {
  /** Имя */
  name?: string | undefined

  /** Должность */
  job?: string | undefined

  /** Текст */
  text?: Document | undefined

  /** картинка */
  image?: Asset | undefined
}

export interface IComands extends Entry<IComandsFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'comands'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IContactsFields {
  /** Заголовок */
  title?: 'телефон' | 'адрес' | 'почта' | undefined

  /** Описание */
  description?: string | undefined

  /** slug */
  slug?: string | undefined
}

export interface IContacts extends Entry<IContactsFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'contacts'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IFooterFields {
  /** Заголовок */
  title?: string | undefined

  /** Текст */
  text?: Document | undefined

  /** Действие */
  action?: string | undefined

  /** Кнопка */
  button?: string | undefined
}

export interface IFooter extends Entry<IFooterFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'footer'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IHomeFields {
  /** Заголовок */
  title?: string | undefined

  /** Подзаголовок */
  subtitle?: Document | undefined

  /** информация */
  info?: string | undefined

  /** акция */
  action?: string | undefined

  /** фон */
  background?: Asset | undefined
}

export interface IHome extends Entry<IHomeFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'home'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IHomeButtonFields {
  /** текст */
  text?: string | undefined
}

export interface IHomeButton extends Entry<IHomeButtonFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'homeButton'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IMapFields {
  /** координаты */
  once?: string | undefined
}

export interface IMap extends Entry<IMapFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'map'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface INavFields {
  /** разделы */
  section?: Document | undefined

  /** Логотип */
  logo?: Asset | undefined
}

export interface INav extends Entry<INavFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'nav'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IPartnerFields {
  /** Заголовок */
  heading?: string | undefined
}

export interface IPartner extends Entry<IPartnerFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'partner'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServiceFields {
  /** Заголовок */
  title?: string | undefined

  /** Текст */
  text?: Document | undefined

  /** картинка */
  image?: Asset | undefined
}

export interface IService extends Entry<IServiceFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'service'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesFields {
  /** Заголовок */
  heading?: string | undefined
}

export interface IServices extends Entry<IServicesFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'services'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesCardFields {
  /** Заголовок */
  title?: string | undefined

  /** Текст */
  text?: Document | undefined

  /** картинка */
  image?: Asset | undefined
}

export interface IServicesCard extends Entry<IServicesCardFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'servicesCard'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE =
  | 'bank'
  | 'comands'
  | 'contacts'
  | 'footer'
  | 'home'
  | 'homeButton'
  | 'map'
  | 'nav'
  | 'partner'
  | 'service'
  | 'services'
  | 'servicesCard'

export type LOCALE_CODE = 'en-US' | 'ru'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
